import './globals.css';
import type { Metadata } from 'next';
import { HeaderComponent } from '@/components/project';
import { Inter } from 'next/font/google';
import ClientOnly from '@/components/common/ClientOnly';
import Footer from '@/components/project/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClientOnly>
        <HeaderComponent />
      </ClientOnly>
      <body className={inter.className}>{children}</body>
      <ClientOnly>
        <Footer />
      </ClientOnly>
    </html>
  );
}
